### ISSUE TITLE
Tooltip for Plan Parameters

### ISSUE THREAD

**Issue by samaraaugust** [BCDA-APS/qs-web2023#10]
Related to Issue #8, show the proper syntax for parameters of some known scans.

**Comment by samaraaugust** [comment]
For example, the list scans parametes are written in this comment: https://github.com/BCDA-APS/qs-web2023/issues/8#issuecomment-1607692494

**Comment by samaraaugust** [comment]
Might already be handled by #8

**Comment by prjemian** [comment]
Looks like this is complete.  Can this issue be closed?
