### ISSUE TITLE
Create a storyboard of the desired GUI

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/qs-web2023#2]
Create a simple sketch of what we think the GUI should look like.

One reference is the `queue-monitor` software, which is a demo PyQt GUI.

**Comment by prjemian** [comment]
As you begin work on this issue, first create a new branch for that work and then put all the work in that branch.

**Comment by keenanlang** [comment]
Reference image from the bluesky queueserver-http project

![](https://raw.githubusercontent.com/bluesky/bluesky-slides/master/assets/qserver-web.png)

https://github.com/bluesky/bluesky-httpserver

**Comment by prjemian** [comment]
Looks like this is complete. Can this issue be closed?
