### ISSUE TITLE
Try to use flask to use bluesky server

### ISSUE THREAD

**Issue by samaraaugust** [BCDA-APS/qs-web2023#6]
references

- https://flask.palletsprojects.com/en/2.3.x/
- https://code.visualstudio.com/docs/python/tutorial-flask
- https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3

**Comment by samaraaugust** [comment]
Possible Question to ask in reference to this file:
https://blueskyproject.io/bluesky-httpserver/configuration.html

Since we are creating a web client that allows users to input information regarding QSERVER_ZMQ_CONTROL_ADDRESS and QSERVER_ZMQ_INFO_ADDRESS, does the server allow for the variables to be changed as the server is running? If so, how?

**Comment by prjemian** [comment]
Re-implementing the bluesky-httpserver project in Python/flask may be a larger project than anticipated.
