### ISSUE TITLE
Automatically construct the position list of some plans

### ISSUE THREAD

**Issue by samaraaugust** [BCDA-APS/qs-web2023#8]
For example: plans such as scan, rel_scan, list_scan have a position argument which is a tuple. For the first two, the tuple consists of a repeating pattern of motor name, start, end positions and there can be n number of these in the tuple. For the last one, the tuple consists of a repeating pattern of motor name and list of position and there can be a n number of these. Other plans involving motors and positions might have different syntax for this tuple. This information was found in the description parameter for a plan in the list of plans.

The objective is that in order to automatically construct the position list, the web client needs to learn the proper syntax for this parameter. The syntax varies between plans. We don't see a machine readable advice about the proper syntax from the plan.

How can the web client or web server know what rule to apply in order to automatically construct the position list from the list of valid positions, let alone the proper values of start and end poisiton values.

**Comment by samaraaugust** [comment]
Suggestion:  include the type of arguments expected by the plan in the kind attribute such as where it states `"value": 2`, include a section that states what the type of values should be. For the example below, we might expect `"type": [MOVEABLE_name, [number]]`

Example (list_scan):
```json
{
  "description": "For one dimension, ``motor, [point1, point2, ....]``.\nIn general:\n\n.. code-block:: python\n\n    motor1, [point1, point2, ...],\n    motor2, [point1, point2, ...],\n    ...,\n    motorN, [point1, point2, ...]\n\nMotors can be any 'settable' object (motor, temp controller, etc.)",
            "kind": {
              "name": "VAR_POSITIONAL",
              "value": 2
            },
            "name": "args"
 }
```

**Comment by prjemian** [comment]
This list is based on some understanding of the `*args, **kwargs` that allow variant parameters used when calling a plan. We cannot determine this list with more information than is provided already by the queueserver.  The queueserver gains its understanding of a plan's argument list by parsing and identifying the data types of each.  By their very nature, the `*args, **kwargs` parameters are non-specific.  The plan's documentation may provide some prose that is descriptive but machine-interpretation of that prose is beyond the skills of the queueserver.

At best, this code could make special cases for recognized plans, such as `count(), fly(), grid_scan(), list_scan(), scan()`` and variants.  For now, do not implement these special cases.  Leave it to the user to use proper syntax for these variant arguments.
